version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      replicas: 1

  whoami:
    image: containous/whoami
    deploy:
      replicas: 3